### ISSUE TITLE
Navigator.OnLine true permanently

### ISSUE THREAD

**Issue by gptucci** [RemiBou/BrowserInterop#101]
Hi
I'm using net5.0 and I'm trying the code in 
https://visualstudiomagazine.com/articles/2020/09/08/blazor-pwa-local-storage.aspx?admgarea=features

I've verified that I get Navigator.OnLine  does not update: permanently returns the same value when the page is refreshed.

OnOnline and OnOffline events (WindowInterop) works perfectly.

Tnx

**Comment by RemiBou** [comment]
I don't think the article content is right. The value will not be updated in the background, you need to get it on the event eg re execute " biNavigator = await biWindow.Navigator();"

**Comment by gptucci** [comment]
Really tnx
