### ISSUE TITLE
Could not find 'browserInterop' in 'window'

### ISSUE THREAD

**Issue by phoenicisf** [RemiBou/BrowserInterop#29]
i found Error: Microsoft.JSInterop.JSException: Could not find 'browserInterop' in 'window'.
Error: Could not find 'browserInterop' in 'window'.

On linux server.

**Comment by RemiBou** [comment]
Thanks for opening this issue, wich method did you call ? Can you give me a quick repro ?

**Comment by phoenicisf** [comment]
```
var windowObjectRef = await JSRuntime.GetInstancePropertyAsync<JsRuntimeObjectRef>("window");
			await JSRuntime.AddEventListener(windowObjectRef, "", "hashchange", CallBackInteropWrapper.Create((Func<JsRuntimeObjectRef, Task>)async delegate (JsRuntimeObjectRef payload)
			{
				var hash = await JSRuntime.InvokeAsync<string>("jsFunctions.getCurrentHash");
				//await window.Console.Log("hash is a {0}", hash);
				if (!String.IsNullOrEmpty(hash) && hash.Length > 1)
				{
					//PdfClickContentFilter(hash);
				}
			}, getDeepObject: true, getJsObjectRef: true));
```

**Comment by andersstorhaug** [comment]
Also ran into this while I was trying out this lib.

Looks like the `_content/BrowserInterop/scripts.js` file isn't included in the NuGet `.nupkg` file.

Not sure why, because according to MS docs with `Microsoft.NET.Sdk.Razor`, everything in `wwwroot` should be packaged by default...

**Comment by RemiBou** [comment]
This is

**Comment by RemiBou** [comment]
This is because I used an unorthodox way for including the script : I load the js resource and call eval() on it. I changed this on master  I just need to fix CI and release the package. If you want to use this call jsInterop.Window() extension method. It'll eval the script

**Comment by RemiBou** [comment]
https://www.nuget.org/packages/BrowserInterop/0.1.5
You can now reference the js file
@phoenicisf I also added handler for hashchange, thanks for the feedback :)

**Comment by taublast** [comment]
It still has this error in Waterfox 64 bit windows 10..

**Comment by RemiBou** [comment]
Did you add the reference to the js file in your index.html file ? Can you
send a repro here or to my mail bourgarel.remi@gmail.com ?

**Comment by taublast** [comment]
Just took your sample project and lib from github, you have the repro. :) VS 2019, in google chrome it is working fine, waterfox fails.. Now the question is, does it the same for everyone?

**Comment by RemiBou** [comment]
I didn't test it with Waterfox (I didn't know it even existed until this issue and I first thought about a typo ^^). 

Indeed I can see the error it's due to this syntax
```js
 serializationSpec = serializationSpec ?? "*";
```

It seems to be fine on other browser but I'll fix it. Let me run the test and deploy a patch

**Comment by RemiBou** [comment]
Fixed in https://www.nuget.org/packages/BrowserInterop/1.0.2

**Comment by taublast** [comment]
Merci et bravo, ce plugin est top :)
