### ISSUE TITLE
SetJSRuntime inconsistent

### ISSUE THREAD

**Issue by grahamehorner** [RemiBou/BrowserInterop#43]
In the code the casing of SetJSRuntime is inconsistent mixture of SetJSRuntime/SetJsRuntime; please consider using consistent casing and/or using an interface/abstract class to enforce the standard.

**Comment by RemiBou** [comment]
Thanks for the feedback, there is already an issue tracking this https://github.com/RemiBou/BrowserInterop/issues/9 . I'm currently working on https://github.com/RemiBou/BrowserInterop/issues/8, you can find the issues that will be resolved before V1 here https://github.com/RemiBou/BrowserInterop/issues?q=is%3Aissue+is%3Aopen+label%3AV1

**Comment by RemiBou** [comment]
This has been fixed for SetJsRuntime, it'll be available in V1, I might release a 0.1.9 before
