### ISSUE TITLE
How to use library wrap method to wrap cusom JavaScrip library

### ISSUE THREAD

**Issue by redradist** [RemiBou/BrowserInterop#56]
Hi,

I am interesting in using your library also as technology to wrap custom JavaScript library, because you already have all needed functionality as container for storing JavaScript object and so on ...

Is there example how to do this ?

**Comment by RemiBou** [comment]
WindowInterop is the best example. Which lib are you thinking about ?

**Comment by redradist** [comment]
@RemiBou I cannot figure out how to use `serializationSpec` ?
```
CallBackInteropWrapper.Create<DeviceMotionEvent>(
                    async e => { await callback.Invoke(e); },
                    getJsObjectRef: false,
                    serializationSpec: new
                    {
                        acceleration = "*",
                        accelerationIncludingGravity = "*",
                        rotationRate = "*",
                        interval = "*"
                    })
```

And also I use the following code:
```javascript
let callbackObj = {
    type: "String",
};
function setCallback(callback) {
    console.log(callback.toString());
    console.log("Before callback");
    callback();
    console.log("After callback");
}

window.setCallback = setCallback;
```
```csharp
        public static async ValueTask Test(IJSRuntime jsRuntime)
        {
            var callback = CallBackInteropWrapper.Create(
                async () =>
            {
                Console.WriteLine("Hello from C# callback !!");
            }
            );
            await jsRuntime.InvokeAsync<JsRuntimeObjectRef>(
                "setCallback",
                callback);
        }
```
And got the following error that callback is not function ...

**Comment by RemiBou** [comment]
Can you create a small repo with the full code ? so I can clone it and debug it like that it's not easy. 

About the serializationSpec, did you have a look at this wiki page :https://github.com/RemiBou/BrowserInterop/wiki/Utility-methods

**Comment by redradist** [comment]
> 
> 
> Can you create a small repo with the full code ? so I can clone it and debug it like that it's not easy.
> 
> About the serializationSpec, did you have a look at this wiki page :https://github.com/RemiBou/BrowserInterop/wiki/Utility-methods

@RemiBou Thanks for documentation !!

Here is simple test example https://github.com/redradist/TestRepo

**Comment by redradist** [comment]
@RemiBou 
> 
> 
> Can you create a small repo with the full code ? so I can clone it and debug it like that it's not easy.
> 
> About the serializationSpec, did you have a look at this wiki page :https://github.com/RemiBou/BrowserInterop/wiki/Utility-methods

Thanks for support !!
I have fixed issue, it was due to that I import script before `<script src="_framework/blazor.webassembly.js"></script>`

When I have removed all scripts after `blazor.webassembly.js` code starts work !!

Also your library is very cool, it simplify wrapping around JavaScript a lot !!

Thanks ;)

**Comment by RemiBou** [comment]
Your welcome, happy you could fix your issue :)

**Comment by redradist** [comment]
@RemiBou 
> 
> 
> WindowInterop is the best example. Which lib are you thinking about ?

If you intrested I am working on [https://github.com/redradist/BlazorGooglePay](BlazorGooglePay)
