### ISSUE TITLE
[Suggestion] Consider using BlazorDependencies

### ISSUE THREAD

**Issue by redradist** [RemiBou/BrowserInterop#60]
@RemiBou Recently I have created small library that simplify Razor Class Library dependency management

https://github.com/redradist/BlazorDependencies
https://medium.com/@redradist/blazor-dependencies-d5597d07ebef

Using it user may not to manually add all script dependencies to index.hmtl ;)

**Comment by RemiBou** [comment]
At first I included the scripts.js as a resource and then called eval on it, but it caused some problem. 

The documented way to include those resources is to use script tag, the user can also bundle the scripts with its other tools like webpack, I think it's not a big deal and I want to keep the dependencies level to the minimum, so we'll keep it as is. 

But people can use your lib with BrowserInterop anyway.

**Comment by redradist** [comment]
> 
> 
> At first I included the scripts.js as a resource and then called eval on it, but it caused some problem.
> 
> The documented way to include those resources is to use script tag, the user can also bundle the scripts with its other tools like webpack, I think it's not a big deal and I want to keep the dependencies level to the minimum, so we'll keep it as is.
> 
> But people can use your lib with BrowserInterop anyway.

But using https://github.com/redradist/BlazorDependencies you are not enforce users to use only BlazorDependencies

User will be able to add script directly or to specify in blazorDeps.json:

```json
[
  {
    "type": "Razor Class Library",
    "name": "BrowserInterop"
  }
]
```

Nobody enforce users to use BlazorDependencies, it is just convenient option ;)
