### ISSUE TITLE
[Feature Request] Add HTML DOM API

### ISSUE THREAD

**Issue by redradist** [RemiBou/BrowserInterop#61]
It would be nice to have ability to access DOM elements and based on this API could be written lots of C# Blazor UI Libraries

**Comment by RemiBou** [comment]
I don't think it would actually be a good idea : Blazor is already here for manipulating the dom. Manipulating the dom outside of Razor files would lead to unwanted result as Blazor internal state would not be in sync with the browser's. 

If there is stuff in the DOM api that can't be done with Blazor, are not planned to be done and do not fit Blazor role then I'd be happy to implement it though.

**Comment by redradist** [comment]
> 
> 
> I don't think it would actually be a good idea : Blazor is already here for manipulating the dom. Manipulating the dom outside of Razor files would lead to unwanted result as Blazor internal state would not be in sync with the browser's.
> 
> If there is stuff in the DOM api that can't be done with Blazor, are not planned to be done and do not fit Blazor role then I'd be happy to implement it though.

@RemiBou Yeah, yesterday after I have write this feature request I also thought about this ... if is it needed ...

But I anyway think it will be useful to have this API available,, then based on mono.wasm it would be possible to implement other frameworks and it will give community lots of choice ...

Also I have been thinking how to improve adding new API ... and I have started new project [BlazorTypeScriptGenerator](https://github.com/redradist/BlazorTypeScriptGenerator)

There are some issues that right now I do not know how to solve, but when I done it will will take a few second to generate wrappers for some API not only Browser API ;)

**Comment by RemiBou** [comment]
Indeed it can be useful on some cases, but it could also do harm. I prefer to keep it that way : if some browser stuff can't be done with Blazor vanilla, I'll think about it. 

In my mind, the purpose of BrowserInterop is not to be able to create wrapper for frameworks but provide API for playing with the browser without going through the pain I've been through. A bit like system API enable to interact with the OS.

I'll close this for now. FYI I identified some window.document API that would be valuable here https://github.com/RemiBou/BrowserInterop/issues/12 . If you need more, please comment on the issue

**Comment by redradist** [comment]
> 
> 
> Indeed it can be useful on some cases, but it could also do harm. I prefer to keep it that way : if some browser stuff can't be done with Blazor vanilla, I'll think about it.
> 
> In my mind, the purpose of BrowserInterop is not to be able to create wrapper for frameworks but provide API for playing with the browser without going through the pain I've been through. A bit like system API enable to interact with the OS.
> 
> I'll close this for now. FYI I identified some window.document API that would be valuable here #12 . If you need more, please comment on the issue

@RemiBou I still think that it is useful to provide all DOM API to user and here is why:

1. There are lots of use-cases which we cannot and event should not imagine (because otherwise we would write this :) ) that particular designer may try to implement and allowing whole DOM API to user is helps with transition from other JavaScript framework to Blazor
2. One of use-cases could be to implement framework in framework for example for animation
Imagine some Blazor component that allow create very cool animations that requires some specific DOM API
If DOM API will be provided partially that each user will try to create issue for implementing its API and you will have a lots of issues (tickets:) )
3. I love open-source and lots of choices that it provides .... The best systems I have worked just provided consistent API without enforcing user to write code only using part of API ...
For example Python allows to write software in such way that you want, you can do whatever you want on that platforms where Python is supported, but each feature is provided consistent to each other

I think that we should not enfore users to write code as we want, but to provide choose ... If user f**cked up, it is not our business, we provided API, you bad implementation is your decision ;)
