### ISSUE TITLE
Window events

### ISSUE THREAD

**Issue by RemiBou** [RemiBou/BrowserInterop#8]
Item for tracking progress on window event wraping. Here is the list of event I plan on implementing :

- [x] window.onappinstalled
- [x] Window.onbeforeinstallprompt
- [x] Window.ondevicemotion
- [x] Window.ondeviceorientation
- [x] onorientationchange
- [x] WindowEventHandlers.onafterprint
- [x] WindowEventHandlers.onbeforeprint
- [x] WindowEventHandlers.onbeforeunload
- [x] GlobalEventHandlers.onblur
- [x] GlobalEventHandlers.onclose
- [x] GlobalEventHandlers.oncontextmenu
- [x] GlobalEventHandlers.onerror
- [x] GlobalEventHandlers.onfocus
- [x] WindowEventHandlers.onhashchange
- [x] WindowEventHandlers.onlanguagechange
- [x] GlobalEventHandlers.onload=
- [x] WindowEventHandlers.onoffline
- [x] WindowEventHandlers.ononline
- [x] WindowEventHandlers.onpagehide
- [x] WindowEventHandlers.onpageshow
- [x] WindowEventHandlers.onpopstate
- [x] GlobalEventHandlers.onresize
- [x] GlobalEventHandlers.onscroll
- [x] GlobalEventHandlers.onwheel
- [x] WindowEventHandlers.onstorage
- [x] WindowEventHandlers.onunload

Documentation https://developer.mozilla.org/en-US/docs/Web/API/Window#Events

**Comment by phoenicisf** [comment]
i request for 'hashchange'

**Comment by RemiBou** [comment]
@phoenicisf it's in the list :  WindowEventHandlers.onhashchange

**Comment by RemiBou** [comment]
All event were implemented. Copy/paste API won'tmake it to v1 (#49), le'ts wait for community feedback to see if needed
