### ISSUE TITLE
How to invoke a constructor of a JS / Typescript class

### ISSUE THREAD

**Issue by TFTomSun** [RemiBou/BrowserInterop#90]
First of all, thanks for your efforts. I like if someone puts effort into making JS Interop more easy to use. 

I didn't find any possibility to invoke a constructor of a class. Is that feature missing?

**Comment by RemiBou** [comment]
I think it would require a bit of code , or to create static factory method

**Comment by TFTomSun** [comment]
I found a way using a on the fly created function using eval, which calls then 

```
 browserInterop.getInstancePropertyRef(${constructorCode},'');
´´´

and calling this function afterwards always

**Comment by RemiBou** [comment]
going to close this. If you think this should be supported in BrowserInterop we can talk about it
