### ISSUE TITLE
Geolocation - Latitude / Longitude

### ISSUE THREAD

**Issue by drma-dev** [RemiBou/BrowserInterop#95]
These attributes are in decimal. Why not double? it would be the most suitable type.

**Comment by RemiBou** [comment]
That's a good question, why do you think it would be more suitable ?

**Comment by drma-dev** [comment]
* decimal occupies 16 bytes, against 8 bytes of double (so there is no point saving this format in the database).
* the double precision is more than enough to store the latitude / longitude values
* some components that work with coordinates, use double. ex: https://github.com/bchavez/Bogus

**Comment by RemiBou** [comment]
From what I've read you seem right. Do you see any major breaking change if I change it? (besides "decimal coord = coordinates.Latitude" which I can live with)

**Comment by drma-dev** [comment]
I don't think I understand the question. I started working with this component now. I don't know any other modules.

**Comment by RemiBou** [comment]
I fixed it in https://www.nuget.org/packages/BrowserInterop/1.1.2
