### ISSUE TITLE
Uncaught ReferenceError: DotNet is not defined

### ISSUE THREAD

**Issue by drma-dev** [RemiBou/BrowserInterop#96]
```
Uncaught ReferenceError: DotNet is not defined
    at new <anonymous> (scripts.js:29)
    at scripts.js:2
```

I am using .NET 5. Maybe it is the reason for the error.

**Comment by RemiBou** [comment]
It can be, I'll work on the update to .net 5 soon for v1.2

**Comment by jgilm** [comment]
I got this same error. I was able to fix it just by moving the script.js reference below the blazor webassembly script reference:

```csharp
    <script src="_framework/blazor.webassembly.js"></script>
    <script>navigator.serviceWorker.register('service-worker.js');</script>

    <script src="_content/BrowserInterop/scripts.js"></script>
```

**Comment by RemiBou** [comment]
@jgilm yes it should always be setup like this. I'll update the doc. @drma-dev is it your problem ?

**Comment by drma-dev** [comment]
@RemiBou  yes, thanks
